spring:
  profiles:
    active: production

  application:
    name: xyy-user-server

  datasource:
    driver-class-name: com.mysql.jdbc.Driver

---
server:
  port: 6845

spring:
  profiles: development

  datasource:
    druid:
      url: jdbc:mysql://192.168.1.106:3306/user-center?characterEncoding=utf-8&useSSL=true
      username: root
      password: hm159357

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://xyy:xyy159357@${eureka.instance.hostname}:8761/eureka/

---
server:
  port: 5184

spring:
  profiles: testing

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://xyy:xyy258456@${eureka.instance.hostname}:9831/eureka/

---
server:
  port: 29100

spring:
  profiles: production

  datasource:
    druid:
      url: jdbc:mysql://iot.ghome.ink:5200/user-center?characterEncoding=utf-8&useSSL=true
      username: root
      password: smartplaything5200

eureka:
  instance:
    hostname: iot.ghome.ink
  client:
    serviceUrl:
      defaultZone: http://chentd:ctd1992@${eureka.instance.hostname}:19820/eureka/