spring:
  profiles:
    active: development

  application:
    name: xyy-user-server

  datasource:
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-value: Y
      logic-not-delete-value: N
      # 是否大写命名
      capital-mode: ${spring.datasource.capital-mode:false}
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 输出日志到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

---
server:
  port: 6845

spring:
  profiles: development

  datasource:
    druid:
      url: jdbc:mysql://192.168.43.97:3306/xyy_user?characterEncoding=utf-8&useSSL=true
      username: root
      password: hm159357

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://xyy:xyy159357@${eureka.instance.hostname}:8761/eureka/

---
server:
  port: 5184

spring:
  profiles: testing

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://xyy:xyy258456@${eureka.instance.hostname}:9831/eureka/

---
server:
  port: 29100

spring:
  profiles: production

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://chentd:ctd1992@${eureka.instance.hostname}:19820/eureka/