spring:
  profiles:
    active: development

  application:
    name: xyy-user-server

  datasource:
    driver-class-name: com.mysql.jdbc.Driver


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  typeAliasesPackage: com.xyy.user.server.domian.**
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: false
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #逻辑删除配置
    logic-delete-value: Y
    logic-not-delete-value: N
    #自定义填充策略接口实现
    #meta-object-handler: com.gzedu.ecloud.common.config.BaseMetaObjectHandler
    # 是否大写命名
    capital-mode: ${spring.datasource.capital-mode:false}
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 输出日志到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

---
server:
  port: 6845

spring:
  profiles: development

  datasource:
    druid:
      url: jdbc:mysql://192.168.1.107:3306/xyy_user?characterEncoding=utf-8&useSSL=true
      username: root
      password: hm159357

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://xyy:xyy159357@${eureka.instance.hostname}:8761/eureka/

---
server:
  port: 5184

spring:
  profiles: testing

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://xyy:xyy258456@${eureka.instance.hostname}:9831/eureka/

---
server:
  port: 29100

spring:
  profiles: production

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://chentd:ctd1992@${eureka.instance.hostname}:19820/eureka/