spring:
  profiles:
    active: development

  application:
    name: xyy-user-server

  datasource:
    druid:
      driverClassName: com.mysql.jdbc.Driver
      # 初始化大小，最小，最大
      initial-size: 50
      minIdle: 20
      maxActive: 100
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      #spring.datasource.useGlobalDataSourceStat=true

      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.json,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
        #allow: 127.0.0.1 # IP白名单
        #deny:  # IP黑名单

---
server:
  port: 6845

spring:
  profiles: development

  datasource:
    druid:
      url: jdbc:mysql://192.168.43.97:3306/xyy_user?characterEncoding=utf-8&useSSL=true
      username: root
      password: hm159357

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://xyy:xyy159357@${eureka.instance.hostname}:8761/eureka/

---
server:
  port: 5184

spring:
  profiles: testing

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://xyy:xyy258456@${eureka.instance.hostname}:9831/eureka/

---
server:
  port: 29100

spring:
  profiles: production

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://chentd:ctd1992@${eureka.instance.hostname}:19820/eureka/